### PR TITLE
[add] Yunohost badge

### PR DESCRIPTION
**Pull request by frju365**
Ofc course, it's open to a debate. I didn't know if I had to add it and where to add it in the README.

### CODE REVIEW

**Comment by charlesabarnes** [comment]
How does this work? Is this something that will need to be kept up and monitored?  I like the idea however!

**Comment by frju365** [comment]
so, Yunohost is software which makes easy selfhosting (for ppl and company).  The URL/badge here allows you to install SPFtoolBox package/app on you instance of Yunohost. So, no need to update it or change it (if you have a Yunohost instance, it will automatically install it on your instance. I maintain the package, and so, update versions on my side (if you want to help you are welcome, even if there are only app_src URL which I have to update) : https://github.com/YunoHost-Apps/spftoolbox_ynh .

**Comment by charlesabarnes** [comment]
Merging this, hoping to also get Heroku and similar integrations working.

**Comment by frju365** [comment]
Thanks !

**Pull request merged**
