### PR TITLE
Display default port if port field is empty

### LINKED ISSUE #30: Display every port if $port is empty
I was thinking, that if var $port is empty, the app shouldn't display nothing, but every port in a list.

What do you think of it ?

### PR DESCRIPTION
**Pull request by frju365**
fixes #30

### CODE REVIEW

**Comment by frju365** [comment]
There are some commit because I merged modifications.

**Comment by frju365** [comment]
I don't know if you need  any screenshot. These are the same as the other PR I did.

**Comment by frju365** [comment]
ping @charlesabarnes ;)

**Comment by frju365** [comment]
I did two screenshot, because I'm thinking that doing "Port ..." is perhaps too much as there is no much place in the first column. Can you tell me you point of view and what do you prefer between these two screenshots ?
1/
image

2/ 
image

**Comment by frju365** [comment]
I did modifications here for the second screenshot.

**Comment by charlesabarnes** [comment]
I like the first one more.

**Comment by frju365** [comment]
ok. Done and tested : 
image

**Comment by frju365** [comment]
ping ? :)

**Pull request merged**
