### PR TITLE
Update index.php and CSS

### PR DESCRIPTION
**Pull request by kawanuaid**
Some optimization and fix HTML5 based  structure, upgrade Bootstrap version from v3 to v4.

### CODE REVIEW

**Comment by charlesabarnes** [comment]
Heya, do you have this up on heroku or anything so I can visually review?

**Comment by kawanuaid** [comment]
> 
> 
> Heya, do you have this up on heroku or anything so I can visually review?

Sure, please visit [https://kawanua-toolbox.herokuapp.com/](https://kawanua-toolbox.herokuapp.com/)
However, there is a mixed content warning issue with some file in **operations** folder.

**Comment by charlesabarnes** [comment]
looks like the CSS is a bit weird on the open port operation

**Comment by kawanuaid** [comment]
[](https://kawanua-toolbox.herokuapp.com/)

> 
> 
> looks like the CSS is a bit weird on the open port operation

Thanks for pointing that out. I just noticed that. Let me fix that.

**Pull request merged**
