### PR TITLE
Heroku App badge

### PR DESCRIPTION
**Pull request by frju365**

### CODE REVIEW

**Comment by frju365** [comment]
Some other things are surely needed... :) https://devcenter.heroku.com/articles/heroku-button

**Comment by charlesabarnes** [comment]
Hey thanks.  I am going to try to implement the heroku side of it all this weekend

**Comment by charlesabarnes** [comment]
Heya, it should be some easy changes, did you wanna make the changes or did you want me to?

Pretty much need to change index.html to be a php file.

It currently isn't detecting that its a php app.

**Comment by charlesabarnes** [comment]
actually I'll make the changes

**Comment by frju365** [comment]
Well, I could do it... as it was easy ;-)

Does it work now ?

**Comment by charlesabarnes** [comment]
Yes it does. Thanks for the contribution

**Pull request merged**
